server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: microservicios-gateway
  cloud:
    gateway:
      routes:
        - id: microservicio-usuarios
          uri: lb://microservicios-usuarios
          predicates:
            - Path=/api/alumnos/**
        - id: microservicio-cursos
          uri: lb://microservicios-cursos
          predicates:
            - Path=/api/cursos/**